server:
  port: 8761          # Le port standard des annuaires Eureka

spring:
  application:
    name: discovery-service  # Le nom du service

eureka:
  client:
    register-with-eureka: false #Je suis le serveur, je ne m'enregistre pas moi-même
    fetch-registry: false       # Je n'ai pas besoin de télécharger l'annuaire, c'est MOI l'annuaire